# https://travis-ci.org/ryanss/vim-hackernews

language: vim

env:
    - PYVERSION=2
    - PYVERSION=3

install:
    - sudo pip install flake8

before_script:
    - flake8 ftplugin/hackernews.py
    - if [ $PYVERSION = 3 ]; then
        git clone https://github.com/vim/vim.git;
        cd vim;
        ./configure --enable-python3interp;
        make;
        sudo make install;
        sudo cp /usr/local/bin/vim /usr/bin/vim;
        cd -;
      fi
    - git clone https://github.com/junegunn/vader.vim.git

script: |
  vim -Nu <(cat << VIMRC
  filetype off
  set rtp+=vader.vim
  set rtp+=.
  filetype plugin indent on
  syntax enable
  VIMRC) -c 'Vader! tests.vader' > /dev/null
